---
name: Generate Profile Metrics

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Ansh-Patoliya
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          # Languages plugin
          plugin_languages: true
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # Activity plugin
          plugin_activity: true
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all

          # Achievements plugin
          plugin_achievements: true
          plugin_achievements_display: detailed
          plugin_achievements_secrets: true
          plugin_achievements_threshold: C

          # Notable contributions
          plugin_notable: true
          plugin_notable_from: organization

          # Lines of code
          plugin_lines: true

          # Repositories traffic
          plugin_traffic: true